[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts",
    "@foundry-rs/forge-std/=lib/forge-std/",
    "@cyfrin/foundry-devops/=lib/foundry-devops/",
    "@google-cloud/functions-framework/=node_modules/@google-cloud/functions-framework",
    "@smartcontractkit/env-enc/=node_modules/@chainlink/env-enc",
    "@ethers/=node_modules/@thers"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
